### ISSUE TITLE
[Question] which kernel32 that needs to be edited via hex editor?

### ISSUE THREAD

**Issue by Markfeller** [Koodaamo-MareDev/Kernel34#1]
theres 7 different "kernel32" string in the growtopia.exe. do i need to change all to "kernel34"?

also this https://github.com/Koodaamo-MareDev/Kernel34/blob/master/kernel34/kernel32.def should be named "kernel34.def" instead of "kernel32.def"

**Comment by Markfeller** [comment]
nevermind, i changed everything and it is fine.

https://www.youtube.com/watch?v=rfwsMPB7RTE => vid tutorial how to do it (you need to have visual studio with c++ extension to compile the dll)

or maybe @Koodaamo-MareDev should upload the dll. or use [mine](https://github.com/Koodaamo-MareDev/Kernel34/files/9080213/kernel34.zip) if you are feeling risky

**Comment by Koodaamo-MareDev** [comment]
> theres 7 different "kernel32" string in the growtopia.exe. do i need to change all to "kernel34"?
> 
> also this https://github.com/Koodaamo-MareDev/Kernel34/blob/master/kernel34/kernel32.def should be named "kernel34.def" instead of "kernel32.def"

There are multiple instances of the string "kernel32.dll" in the executable. I recommend changing them all to "kernel34.dll"

Regarding the "kernel32.def" you are absolutely right. Since I had issues uploading to GitHub from VS, I had to create a new project, which is why apparently some of the content is outdated. The project file has a reference to kernel32.asm which no longer exists.

I'll update the repo with the updated contents soon. Assuming you got everything working I'll close this issue now.
